include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/comparison.smk"
include: "rules/annotation.smk"

report: "report/workflow.rst"

calls = expand(["results/calls/{sample}.txt"], sample = sample_names)
fastqc = expand(["results/qc/fastqc/{sample}.{read}_fastqc.html"], sample = sample_names, read = ['r1', 'r2'])
mbias_plots = expand(["results/plots/mbias/{sample}_m-bias_fwd.png", "results/plots/mbias/{sample}_m-bias_rev.png"], sample = sample_names)

rule all:
    input:
        output = calls + fastqc
