samples: "config/samples.tsv"

threads: 2

meRanT:
  id2gene: "resources/id2gene/mm10.refSeqRNA-noPRED.500.t2g.map"
  bsidx: "resources/mkbsidx/mm10.refSeqRNA-noPRED.500_C2T"

meRanCall:
  transcript_fasta: "resources/fa/mm10.refSeqRNA-noPRED.500.fa"

