$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples:
    type: string
  threads:
    type: integer
  meRanT:
    type: object
    properties:
      id2gene:
        type: string
      bsidx:
        type: string
  meRanCall:
    type: object
    properties:
      transcript_fasta: 
        type: string

# entries that have to be in the config file for successful validation
required:
  - samples
