$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object
# possible entries of the config file and which type they should be
properties:
  samples:
    type: string
  threads:
    type: integer
  meRanT:
    type: object
    properties:
      index:
        type: object
        properties:
          transcript_fa_url: string
  meRanCall:
    type: object
    properties:
      seq_context_around_meth_c: integer
      min_methlyation_rate: number

# entries that have to be in the config file for successful validation
required:
  - samples
  - threads
  - meRanT
  - meRanCall

