name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.5.3
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1.5.3
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs"
        stagein: '
        wget -O /tmp/meRanTK-1.2.1b.zip https://icbi.i-med.ac.at/software/meRanTK/downloads/1.2.1b/meRanTK-1.2.1b.zip
        unzip /tmp/meRanTK-1.2.1b.zip -d /tmp/
        export $PATH=PATH:/tmp/meRanTK-1.2.1b/:/tmp/meRanTK-1.2.1b/util/:/tmp/meRanTK-1.2.1b/extutil/
        meRanT mkbsidx -fa .test/resources/fa/mm10.refSeqRNA-noPRED.500.fa -id .test/resources/mkbsidx/
        mkRefSeq2GeneMap.pl -f .test/resources/fa/mm10.refSeqRNA-noPRED.500.fa -m .test/resources/id2gene/mm10.refSeqRNA-noPRED.500.t2g.map
        '