name: Pylint

on: [push]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.5.3
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--lint"
